# Generated by Django 2.2.6 on 2021-03-12 12:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=13), size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), size=None)),
                ('sector', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('ol_fees', models.IntegerField()),
                ('al_fees', models.IntegerField()),
                ('students', models.IntegerField(default=0)),
                ('combinations', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(upload_to='images/secondary_school_logos/')),
                ('school_motto', models.CharField(blank=True, default='', max_length=200)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('levels', models.CharField(choices=[('O_LEVEL', 'O_LEVEL'), ('A_LEVEL', 'A_LEVEL'), ('ALL', 'ALL')], default='ALL', max_length=15)),
                ('genders', models.CharField(choices=[('BOYS', 'BOYS'), ('GIRLS', 'GIRLS'), ('ALL', 'ALL')], default='ALL', max_length=15)),
                ('types', models.CharField(choices=[('BOARDING', 'BOARDING'), ('DAYSCHOLAR', 'DAYSCHOLAR'), ('BOTH', 'BOTH')], max_length=10)),
                ('headmaster', models.CharField(max_length=20)),
                ('more_information', models.TextField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondaryapp.Category')),
            ],
        ),
    ]
