# Generated by Django 2.2.3 on 2019-07-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondaryapp', '0002_auto_20190725_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary',
            name='al_fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='ol_fees',
            field=models.IntegerField(),
        ),
    ]
