# Generated by Django 2.2.3 on 2019-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondaryapp', '0003_auto_20190726_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary',
            name='types',
            field=models.CharField(choices=[('BOARDING', 'BOARDING'), ('DAYSCHOLAR', 'DAYSCHOLAR'), ('BOTH', 'BOTH')], max_length=10),
        ),
    ]
