# Generated by Django 2.2.3 on 2019-08-06 07:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondaryapp', '0004_auto_20190731_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='secondary',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
