# Generated by Django 2.2.3 on 2019-08-13 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('secondaryapp', '0005_auto_20190806_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
