# Generated by Django 2.2.3 on 2019-08-15 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondaryapp', '0006_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All',
        ),
        migrations.AlterField(
            model_name='secondary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondaryapp.Category'),
        ),
    ]
