# Generated by Django 2.2.6 on 2021-03-12 12:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=50), size=None)),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
                ('website', models.URLField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('more_info', models.TextField(blank=True)),
                ('log', models.ImageField(upload_to='images/universit_logs/')),
                ('ownershipstatus', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=10)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=200)),
                ('duration', models.IntegerField(default=4)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.University')),
            ],
        ),
        migrations.CreateModel(
            name='Facult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fees', models.IntegerField(default=0)),
                ('course', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('programoffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universite.Program')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facults', to='universite.University')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('head_department', models.CharField(max_length=200)),
                ('contacts', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('facult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universite.Facult')),
            ],
        ),
    ]
