# Generated by Django 2.2.3 on 2019-08-10 23:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=50), size=None)),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
                ('website', models.URLField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('csector', models.CharField(max_length=50)),
                ('key_person', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('more_info', models.TextField(blank=True)),
                ('log', models.ImageField(upload_to='images/universit_logs/')),
                ('ownershipstatus', models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default='public', max_length=10)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
