# Generated by Django 2.2.3 on 2019-08-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=200)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.University')),
            ],
        ),
    ]
