# Generated by Django 2.2.3 on 2019-08-10 23:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fees', models.IntegerField(default=0)),
                ('course', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('programoffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universite.Program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.University')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('headofdepartment', models.CharField(max_length=200)),
                ('contacts', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('facult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universite.Facult')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.University')),
            ],
        ),
    ]
