# Generated by Django 2.2.3 on 2019-08-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0003_department_facult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='csector',
            new_name='sector',
        ),
    ]
