# Generated by Django 2.2.3 on 2019-08-11 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0004_auto_20190810_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
