# Generated by Django 2.2.3 on 2019-08-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0006_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All',
        ),
    ]
