# Generated by Django 2.2.3 on 2019-08-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0007_delete_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
