# Generated by Django 2.2.3 on 2019-08-11 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universite', '0008_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMOdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.Department')),
                ('facult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.Facult')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.Program')),
                ('universitiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
