# Generated by Django 2.2.3 on 2019-08-10 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0010_auto_20190811_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='facult',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facult', to='universite.Facult'),
        ),
        migrations.AlterField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='universite.University'),
        ),
    ]
