# Generated by Django 2.2.3 on 2019-08-11 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0014_auto_20190811_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universite.University'),
        ),
    ]
