# Generated by Django 2.2.3 on 2019-08-11 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0015_auto_20190811_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facults', to='universite.University'),
        ),
    ]
