# Generated by Django 2.2.3 on 2019-08-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0016_auto_20190811_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
        migrations.RemoveField(
            model_name='facult',
            name='university',
        ),
    ]
