# Generated by Django 2.2.3 on 2019-08-11 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0017_auto_20190811_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='facult',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facults', to='universite.Facult'),
        ),
    ]
