# Generated by Django 2.2.3 on 2019-08-11 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0019_department_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='programoffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facults', to='universite.Program'),
        ),
    ]
