# Generated by Django 2.2.3 on 2019-08-11 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0021_auto_20190811_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facult',
            name='university',
        ),
        migrations.AlterField(
            model_name='facult',
            name='programoffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facults', to='universite.Program'),
        ),
    ]
