# Generated by Django 2.2.3 on 2019-08-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0025_auto_20190811_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
