# Generated by Django 2.2.3 on 2019-08-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0026_auto_20190811_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='ownershipstatus',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=10),
        ),
    ]
