# Generated by Django 2.2.3 on 2019-08-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0028_university_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='headofdepartment',
        ),
        migrations.AddField(
            model_name='department',
            name='head_department',
            field=models.CharField(default='murengera', max_length=200),
            preserve_default=False,
        ),
    ]
