# Generated by Django 2.2.3 on 2019-08-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0030_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='facult',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universite.Facult'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
