# Generated by Django 2.2.3 on 2019-08-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0032_auto_20190820_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='university',
        ),
    ]
