# Generated by Django 2.2.3 on 2019-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0033_remove_department_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facult',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
