# Generated by Django 2.2.3 on 2019-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0034_auto_20190820_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facult',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
