# Generated by Django 2.2.6 on 2019-10-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0035_auto_20190820_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.IntegerField(default=4),
        ),
    ]
