# Generated by Django 2.2.6 on 2019-10-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0036_program_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dalton', max_length=20)),
                ('universityname', models.ForeignKey(default='url', on_delete=django.db.models.deletion.CASCADE, to='universite.University')),
            ],
        ),
    ]
