# Generated by Django 2.2.6 on 2019-10-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0037_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dalton', max_length=20)),
                ('universityName', models.ForeignKey(default='ur', on_delete=django.db.models.deletion.CASCADE, to='universite.University')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
