# Generated by Django 2.2.6 on 2019-10-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0038_auto_20191016_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
