# Generated by Django 2.2.6 on 2019-11-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0039_delete_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='user',
        ),
    ]
