# Generated by Django 2.2.6 on 2019-11-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0040_remove_university_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='university',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='university',
            name='key_person',
        ),
    ]
