# Generated by Django 2.2.6 on 2019-11-10 12:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0041_auto_20191110_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='key_person',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
