# Generated by Django 2.2.6 on 2019-11-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0042_auto_20191110_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
