# Generated by Django 2.2.3 on 2019-07-31 13:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='contactapp.Category'),
        ),
    ]
