# Generated by Django 2.2.3 on 2019-08-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_auto_20190731_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_form',
            new_name='ContactForm',
        ),
        migrations.RenameModel(
            old_name='User_Register',
            new_name='UserRegister',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
    ]
