# Generated by Django 2.2.3 on 2019-08-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_subscribe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
