# Generated by Django 2.2.3 on 2019-08-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0005_auto_20190815_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
