# Generated by Django 2.2.6 on 2019-11-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0006_auto_20190816_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
    ]
